theme: jekyll-theme-primer
title: Spotify Playlist Popularity
description: Predicting the popularity of a Spotify playlist
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
